### ISSUE TITLE
note3 crash

### ISSUE THREAD

**Issue by IceHermes** [baoyongzhang/SwipeMenuListView#17]
java.lang.ClassCastException SwipeMenuListView$1 cannot be cast to android.widget.BaseAdapter
 at android.widget.FastScroller.getSectionsFromIndexer(FastScroller.java:875)
            at android.widget.FastScroller.getPosFromItemCount(FastScroller.java:1147)
            at android.widget.FastScroller.onItemCountChanged(FastScroller.java:453)
            at android.widget.AbsListView.onLayout(AbsListView.java:2543)
            at android.view.View.layout(View.java:15664)
            at android.view.ViewGroup.layout(ViewGroup.java:4869)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:15664)
            at android.view.ViewGroup.layout(ViewGroup.java:4869)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
            at android.view.View.layout(View.java:15664)
            at android.view.ViewGroup.layout(ViewGroup.java:4869)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
            at android.view.View.layout(View.java:15664)
            at android.view.ViewGroup.layout(ViewGroup.java:4869)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:15664)
            at android.view.ViewGroup.layout(ViewGroup.java:4869)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
            at android.view.View.layout(View.java:15664)
            at android.view.ViewGroup.layout(ViewGroup.java:4869)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:15664)
            at android.view.ViewGroup.layout(ViewGroup.java:4869)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2246)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1968)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1200)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6401)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
            at android.view.Choreographer.doCallbacks(Choreographer.java:603)
            at android.view.Choreographer.doFrame(Choreographer.java:573)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5335)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by LiuJQ** [comment]
this exception occurs on HUAWEI EMUI 3.0 system too.

**Comment by tahadev** [comment]
has any body solved this !!!?
same here ..
