### ISSUE TITLE
Crash in onTouchEvent

### ISSUE THREAD

**Issue by ngocht143** [baoyongzhang/SwipeMenuListView#71]
Hi Mr Bao, 
Please fix this issue, i always get it after performing a menu item click, then scroll the listview (tested for Android 2.x).
java.lang.ArrayIndexOutOfBoundsException
at android.view.MotionEvent.getY(MotionEvent.java:903)
at android.widget.AbsListView.onTouchEvent(AbsListView.java:2184)
at android.widget.ListView.onTouchEvent(ListView.java:3446)
at com.baoyz.swipemenulistview.SwipeMenuListView.onTouchEvent(SwipeMenuListView.java:112)
at android.view.View.dispatchTouchEvent(View.java:3885)

Looking forward to hear your reply. Thank you.

**Comment by openproject** [comment]
在SwipeMenuListView中的onTouchEvent方法里修改如下，可解决：
     @Override
     public boolean onTouchEvent(MotionEvent ev) {
-        if (ev.getAction() != MotionEvent.ACTION_DOWN && mTouchView == null)
-            return super.onTouchEvent(ev);
+        if (ev.getAction() != MotionEvent.ACTION_DOWN && mTouchView == null) {
+            boolean result = false;
+            try {
+                result = super.onTouchEvent(ev);
+            } catch (Exception e) {
+                e.printStackTrace();
+            }
+            return result;
+        }
...
}

**Comment by ngocht143** [comment]
I'm using gradle compile so i can't edit it, however, i extended SwipeMenuListView to catch this issue
